replicaCount: 1

global:
  image:
    repository: dockercaustav/simple-python-web-app
    tag: "2"
    pullPolicy: IfNotPresent

service1:
  nameOverride: service1
  image:
    repository: dockercaustav/simple-python-web-app
    tag: "2"
    pullPolicy: IfNotPresent
    
service2:
  nameOverride: service2
  image:
    repository: dockercaustav/simple-python-web-app-2
    tag: "2"
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

nodeSelector: {}

tolerations: []

affinity: {}